import os

BOT_TOKEN = os.getenv("BOT_TOKEN", "8977857112:AAESiv1XPOaoFbYapgLVKwd1mUiVjknl3Lo")

# Level Requirements
LEVEL_ACADEMY = 1
LEVEL_PROFILE = 1
LEVEL_HAP = 1
LEVEL_FISHING = 1
LEVEL_SELL_FISH = 1
LEVEL_BANK = 2
LEVEL_CASINO = 3
LEVEL_INVENTORY = 4
LEVEL_SMUGGLE = 4

# XP Settings
XP_PER_LEVEL = 35
HAP_XP_REWARD = 1
FISHING_XP_REWARD = 1
TAME_XP_REWARD = 1
CASINO_XP_REWARD = 1

# Prison Settings
PRISON_DURATION_SEC = 15 * 60  # 15 minutes
DEFAULT_PRISON_FINE = 5000
ESCAPE_SUCCESS_RATE = 0.5